version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: |
          pip install --user -r requirements.txt
          sudo pip install pytest
      - run: |
          pytest -vv -p no:cacheprovider